CREATE TABLE PERMANENT_SERVINGS(
	SERVING_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	RECIPE_ID INT NOT NULL,
	CANTEEN_ID INT NOT NULL,
	FOREIGN KEY(RECIPE_ID) REFERENCES RECIPES(RECIPE_ID),
	FOREIGN KEY(CANTEEN_ID) REFERENCES CANTEENS(CANTEEN_ID)
);

CREATE TABLE SERVINGS(
	SERVING_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SERVING_DATE DATE NOT NULL,
	SOLD_OUT BOOLEAN NOT NULL DEFAULT FALSE,
	RECIPE_ID INT NOT NULL,
	CANTEEN_ID INT NOT NULL,
	FOREIGN KEY(RECIPE_ID) REFERENCES RECIPES(RECIPE_ID),
	FOREIGN KEY(CANTEEN_ID) REFERENCES CANTEENS(CANTEEN_ID)
);

CREATE TABLE RECIPES(
	RECIPE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	RECIPE_NAME VARCHAR(255) NOT NULL,
	DIET ENUM('VEGAN', 'VEGETARIAN', 'PESCETARIAN', 'CARNIVOR') NOT NULL,
	PRICE_STUDENT DOUBLE,
	PRICE_EMPLOYEE DOUBLE,
	PRICE_GUEST DOUBLE,
	CO2_EMISSION INT,
	H2O_EMISSION DOUBLE
);

CREATE TABLE ALLERGENS(
	ALLERGEN_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ALLERGEN_NAME VARCHAR(63) NOT NULL
);

CREATE TABLE ALLGERGEN_RECIPE_RELATION(
	ALLERGEN_ID INT NOT NULL,
	RECIPE_ID INT NOT NULL,
	PRIMARY KEY(ALLERGEN_ID, RECIPE_ID),
	FOREIGN KEY(ALLERGEN_ID) REFERENCES ALLERGENS(ALLERGEN_ID),
	FOREIGN KEY(RECIPE_ID) REFERENCES RECIPES(RECIPE_ID)
);

CREATE TABLE ADDITIVES(
	ADDITIVE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ADDITIVE_NAME VARCHAR(63) NOT NULL
);

CREATE TABLE ADDITIVE_RECIPE_RELATION(
	ADDITIVE_ID INT NOT NULL,
	RECIPE_ID INT NOT NULL,
	PRIMARY KEY(ADDITIVE_ID, RECIPE_ID),
	FOREIGN KEY(ADDITIVE_ID) REFERENCES ADDITIVES(ADDITIVE_ID),
	FOREIGN KEY(RECIPE_ID) REFERENCES RECIPES(RECIPE_ID)
);

CREATE TABLE NUTRIENTS(
	NUTRIENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ENERGY DOUBLE,
	FAT DOUBLE,
	SATURATED_FAT DOUBLE,
	CARBOHYDRATES DOUBLE,
	SUGAR DOUBLE,
	PROTEIN DOUBLE,
	SALT DOUBLE,
	FIBER DOUBLE,
	RECIPE_ID INT NOT NULL,
	FOREIGN KEY(RECIPE_ID) REFERENCES RECIPES(RECIPE_ID)
);

CREATE TABLE RECIPE_IMAGES(
	IMAGE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	IMAGE_URL VARCHAR(255) NOT NULL,
	IS_AI_GENERATED BOOLEAN NOT NULL,
	RECIPE_ID INT NOT NULL,
	FOREIGN KEY(RECIPE_ID) REFERENCES RECIPES(RECIPE_ID)
);

CREATE TABLE RECIPE_RATINGS(
	RATING_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	RATING INT NOT NULL,
	USER_ID UUID NOT NULL,
	RECIPE_ID INT NOT NULL,
	FOREIGN KEY(RECIPE_ID) REFERENCES RECIPES(RECIPE_ID)
);

CREATE TABLE ADDITIONS(
	ADDITION_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ADDITION_NAME VARCHAR(255) NOT NULL,
	DIET ENUM('VEGAN', 'VEGETARIAN', 'PESCETARIAN', 'CARNIVOR') NOT NULL,
	PRICE_STUDENT DOUBLE,
	PRICE_EMPLOYEE DOUBLE,
	PRICE_GUEST DOUBLE,
	RECIPE_ID INT NOT NULL,
	FOREIGN KEY(RECIPE_ID) REFERENCES RECIPES(RECIPE_ID)
);


CREATE TABLE CANTEENS(
	CANTEEN_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CANTEEN_NAME VARCHAR(50) NOT NULL,
	LATITUDE DOUBLE NOT NULL,
	LONGITUDE DOUBLE NOT NULL,
	SLUG VARCHAR(50) NOT NULL
);

CREATE TABLE OPENING_HOURS(
	OPENING_HOURS_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	OPENING_TIME TIME NOT NULL,
	CLOSING_TIME TIME NOT NULL,
	DAY_OF_WEEK ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY') NOT NULL,
	CANTEEN_ID INT NOT NULL,
	FOREIGN KEY(CANTEEN_ID) REFERENCES CANTEENS(CANTEEN_ID)
);

CREATE TABLE CANTEEN_INFO(
	CANTEEN_INFO_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CANTEEN_ID INT NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	META_DESCRIPTION TEXT,
	BODY TEXT,
	FOREIGN KEY(CANTEEN_ID) REFERENCES CANTEENS(CANTEEN_ID)
);

CREATE TABLE CANTEEN_IMAGES(
	IMAGE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	IMAGE_URL VARCHAR(255) NOT NULL,
	CANTEEN_ID INT NOT NULL,
	FOREIGN KEY(CANTEEN_ID) REFERENCES CANTEENS(CANTEEN_ID)
);

CREATE TABLE CANTEEN_RATINGS(
	RATING_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	RATING INT NOT NULL,
	USER_ID UUID NOT NULL,
	CANTEEN_ID INT NOT NULL,
	FOREIGN KEY(CANTEEN_ID) REFERENCES CANTEENS(CANTEEN_ID)
);