services:
  # traefik:
  #   image: traefik:v3.1
  #   command:
  #     - '--providers.docker'
  #     - '--providers.docker.exposedbydefault=false'
  #     - '--entryPoints.websecure.address=:443'
  #     - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
  #     - '--certificatesresolvers.myresolver.acme.email=eric@woven.design'
  #     - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
  #     - '--entrypoints.web.address=:80'
  #     - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
  #     - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
  #   ports:
  #     - mode: host
  #       protocol: tcp
  #       published: 80
  #       target: 80
  #     - mode: host
  #       protocol: tcp
  #       published: 443
  #       target: 443
  #   volumes:
  #     - letsencrypt:/letsencrypt
  #     - /var/run/docker.sock:/var/run/docker.sock

  web:
    image: ghcr.io/ericwaetke/mensaradar:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.web.loadbalancer.server.port=4321'
      # - 'traefik.http.routers.web.rule=Host(`mensa-radar.de`)'
      - 'traefik.http.routers.web.rule=Host(`mensa-radar.de`)'
      - 'traefik.http.routers.web.entrypoints=websecure'
      - 'traefik.http.routers.web.tls.certresolver=myresolver'
    ports:
      - '4321:4321'
    secrets:
      - db-password
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - NITRO_PORT=4321
      - PORT=4321
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db
      - hub

  hub:
    image: ghcr.io/ericwaetke/mensa-hub:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.web.loadbalancer.server.port=3000'
      - 'traefik.http.routers.web.rule=Host(`hub.mensa-radar.de`)'
      - 'traefik.http.routers.web.entrypoints=websecure'
      - 'traefik.http.routers.web.tls.certresolver=myresolver'
    ports:
      - '3000:3000'
    secrets:
      - db-password
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - PAYLOAD_SECRET=43bca53404a4663d51d0a0ee
      - SERVER_URL=http://localhost:3000
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db

  queue:
    image: ghcr.io/ericwaetke/mensa-queue:latest
    secrets:
      - db-password
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db
      - hub

  db:
    image: postgres
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  letsencrypt:

secrets:
  db-password:
    external: true
