services:
    web:
        image: ghcr.io/ericwaetke/mensaradar:latest
        networks:
            - mensaradar
        ports:
            - "4321:4321"
        secrets:
            - db-password
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=app
            - POSTGRES_PORT=5432
            - POSTGRES_SSLMODE=disable
            - NITRO_PORT=4321
            - PORT=4321
        deploy:
            update_config:
                order: start-first
        depends_on:
            - db
            - hub

    hub:
        image: ghcr.io/ericwaetke/mensa-hub:latest
        networks:
            - mensaradar
        ports:
            - "3003:3000"
        secrets:
            - db-password
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=app
            - POSTGRES_PORT=5432
            - POSTGRES_SSLMODE=disable
            - PAYLOAD_SECRET=43bca53404a4663d51d0a0ee
            - SERVER_URL=https://hub.mensa-radar.de
        deploy:
            update_config:
                order: start-first
        depends_on:
            - db

    queue:
        image: ghcr.io/ericwaetke/mensa-queue:latest
        networks:
            - mensaradar
        secrets:
            - db-password
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=app
            - POSTGRES_PORT=5432
            - POSTGRES_SSLMODE=disable
        # deploy:
        #   update_config:
        #     order: start-first
        depends_on:
            - db
            - hub

    db:
        image: postgres
        networks:
            - mensaradar
        user: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        secrets:
            - db-password
        environment:
            - POSTGRES_DB=app
            - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - "5432:5432"

volumes:
    db-data:
    letsencrypt:

networks:
    mensaradar:
        driver: overlay
    nginx:
        external: true

secrets:
    db-password:
        external: true
