name: Revalidate Mensa Data Cron Job
on:
  schedule:
    - cron: '0/5 7,8,9,10,11,12,13,14 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Revalidation API
        run: |
          curl --request POST \
          --url 'https://next.mensa-radar.de/api/revalidate' \
          --header 'Authorization: Bearer ${{ secrets.REVALIDATION_TOKEN }}'