name: Revalidate Mensa Data Cron Job
on:
  workflow_dispatch:
  # schedule:
    #- cron: '*/5 7-14 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Revalidation API
        run: |
          curl --request POST \
          --url 'https://mensa-radar.de/api/revalidate' \
          --header "Authorization: Bearer ${{ secrets.REVALIDATION_TOKEN }}"
